// <auto-generated />
using System;
using BookStore.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Infrastructure.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20231218195405_SeedCategory")]
    partial class SeedCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(350)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("BookStore.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Category 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Category 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Category 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Category 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Category 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Category 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Category 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Category 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Category 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Category 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Category 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Category 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Category 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Category 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Category 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Category 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Category 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Category 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Category 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Category 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Category 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Category 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Category 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Category 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Category 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Category 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Category 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Category 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Category 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Category 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Category 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Category 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Category 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Category 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Category 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Category 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Category 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Category 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Category 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Category 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Category 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Category 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Category 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Category 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Category 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Category 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Category 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Category 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Category 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Category 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Category 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Category 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Category 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Category 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Category 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Category 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Category 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Category 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Category 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Category 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Category 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Category 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Category 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Category 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Category 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Category 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Category 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Category 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Category 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Category 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Category 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Category 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Category 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Category 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Category 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Category 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Category 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Category 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Category 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Category 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Category 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Category 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Category 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Category 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Category 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Category 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Category 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Category 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Category 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Category 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Category 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Category 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Category 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Category 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Category 100"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Category 101"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Category 102"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Category 103"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Category 104"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Category 105"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Category 106"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Category 107"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Category 108"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Category 109"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Category 110"
                        });
                });

            modelBuilder.Entity("BookStore.Domain.Models.Book", b =>
                {
                    b.HasOne("BookStore.Domain.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookStore.Domain.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
