// <auto-generated />
using System;
using BookStore.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Infrastructure.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20231218204851_SeedBook")]
    partial class SeedBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(350)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            CategoryId = 1,
                            Description = "Test 1",
                            Name = "Book 1",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            CategoryId = 1,
                            Description = "Test 2",
                            Name = "Book 2",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            CategoryId = 1,
                            Description = "Test 3",
                            Name = "Book 3",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            CategoryId = 1,
                            Description = "Test 4",
                            Name = "Book 4",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            CategoryId = 1,
                            Description = "Test 5",
                            Name = "Book 5",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            CategoryId = 1,
                            Description = "Test 6",
                            Name = "Book 6",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            CategoryId = 1,
                            Description = "Test 7",
                            Name = "Book 7",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            CategoryId = 1,
                            Description = "Test 8",
                            Name = "Book 8",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            CategoryId = 1,
                            Description = "Test 9",
                            Name = "Book 9",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            CategoryId = 1,
                            Description = "Test 10",
                            Name = "Book 10",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 11",
                            CategoryId = 1,
                            Description = "Test 11",
                            Name = "Book 11",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 12",
                            CategoryId = 1,
                            Description = "Test 12",
                            Name = "Book 12",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 13",
                            CategoryId = 1,
                            Description = "Test 13",
                            Name = "Book 13",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 14",
                            CategoryId = 1,
                            Description = "Test 14",
                            Name = "Book 14",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 15",
                            CategoryId = 1,
                            Description = "Test 15",
                            Name = "Book 15",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 16,
                            Author = "Author 16",
                            CategoryId = 1,
                            Description = "Test 16",
                            Name = "Book 16",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 17,
                            Author = "Author 17",
                            CategoryId = 1,
                            Description = "Test 17",
                            Name = "Book 17",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 18,
                            Author = "Author 18",
                            CategoryId = 1,
                            Description = "Test 18",
                            Name = "Book 18",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 19,
                            Author = "Author 19",
                            CategoryId = 1,
                            Description = "Test 19",
                            Name = "Book 19",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 20,
                            Author = "Author 20",
                            CategoryId = 1,
                            Description = "Test 20",
                            Name = "Book 20",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 21,
                            Author = "Author 21",
                            CategoryId = 1,
                            Description = "Test 21",
                            Name = "Book 21",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 22,
                            Author = "Author 22",
                            CategoryId = 1,
                            Description = "Test 22",
                            Name = "Book 22",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 23,
                            Author = "Author 23",
                            CategoryId = 1,
                            Description = "Test 23",
                            Name = "Book 23",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 24,
                            Author = "Author 24",
                            CategoryId = 1,
                            Description = "Test 24",
                            Name = "Book 24",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 25,
                            Author = "Author 25",
                            CategoryId = 1,
                            Description = "Test 25",
                            Name = "Book 25",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 26,
                            Author = "Author 26",
                            CategoryId = 1,
                            Description = "Test 26",
                            Name = "Book 26",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 27,
                            Author = "Author 27",
                            CategoryId = 1,
                            Description = "Test 27",
                            Name = "Book 27",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 28,
                            Author = "Author 28",
                            CategoryId = 1,
                            Description = "Test 28",
                            Name = "Book 28",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 29,
                            Author = "Author 29",
                            CategoryId = 1,
                            Description = "Test 29",
                            Name = "Book 29",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 30,
                            Author = "Author 30",
                            CategoryId = 1,
                            Description = "Test 30",
                            Name = "Book 30",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 31,
                            Author = "Author 31",
                            CategoryId = 1,
                            Description = "Test 31",
                            Name = "Book 31",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 32,
                            Author = "Author 32",
                            CategoryId = 1,
                            Description = "Test 32",
                            Name = "Book 32",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 33,
                            Author = "Author 33",
                            CategoryId = 1,
                            Description = "Test 33",
                            Name = "Book 33",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 34,
                            Author = "Author 34",
                            CategoryId = 1,
                            Description = "Test 34",
                            Name = "Book 34",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 35,
                            Author = "Author 35",
                            CategoryId = 1,
                            Description = "Test 35",
                            Name = "Book 35",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 36,
                            Author = "Author 36",
                            CategoryId = 1,
                            Description = "Test 36",
                            Name = "Book 36",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 37,
                            Author = "Author 37",
                            CategoryId = 1,
                            Description = "Test 37",
                            Name = "Book 37",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 38,
                            Author = "Author 38",
                            CategoryId = 1,
                            Description = "Test 38",
                            Name = "Book 38",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 39,
                            Author = "Author 39",
                            CategoryId = 1,
                            Description = "Test 39",
                            Name = "Book 39",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 40,
                            Author = "Author 40",
                            CategoryId = 1,
                            Description = "Test 40",
                            Name = "Book 40",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 41,
                            Author = "Author 41",
                            CategoryId = 1,
                            Description = "Test 41",
                            Name = "Book 41",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 42,
                            Author = "Author 42",
                            CategoryId = 1,
                            Description = "Test 42",
                            Name = "Book 42",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 43,
                            Author = "Author 43",
                            CategoryId = 1,
                            Description = "Test 43",
                            Name = "Book 43",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 44,
                            Author = "Author 44",
                            CategoryId = 1,
                            Description = "Test 44",
                            Name = "Book 44",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 45,
                            Author = "Author 45",
                            CategoryId = 1,
                            Description = "Test 45",
                            Name = "Book 45",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 46,
                            Author = "Author 46",
                            CategoryId = 1,
                            Description = "Test 46",
                            Name = "Book 46",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 47,
                            Author = "Author 47",
                            CategoryId = 1,
                            Description = "Test 47",
                            Name = "Book 47",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 48,
                            Author = "Author 48",
                            CategoryId = 1,
                            Description = "Test 48",
                            Name = "Book 48",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 49,
                            Author = "Author 49",
                            CategoryId = 1,
                            Description = "Test 49",
                            Name = "Book 49",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 50,
                            Author = "Author 50",
                            CategoryId = 1,
                            Description = "Test 50",
                            Name = "Book 50",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 51,
                            Author = "Author 51",
                            CategoryId = 1,
                            Description = "Test 51",
                            Name = "Book 51",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 52,
                            Author = "Author 52",
                            CategoryId = 1,
                            Description = "Test 52",
                            Name = "Book 52",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 53,
                            Author = "Author 53",
                            CategoryId = 1,
                            Description = "Test 53",
                            Name = "Book 53",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 54,
                            Author = "Author 54",
                            CategoryId = 1,
                            Description = "Test 54",
                            Name = "Book 54",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 55,
                            Author = "Author 55",
                            CategoryId = 1,
                            Description = "Test 55",
                            Name = "Book 55",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 56,
                            Author = "Author 56",
                            CategoryId = 1,
                            Description = "Test 56",
                            Name = "Book 56",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 57,
                            Author = "Author 57",
                            CategoryId = 1,
                            Description = "Test 57",
                            Name = "Book 57",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 58,
                            Author = "Author 58",
                            CategoryId = 1,
                            Description = "Test 58",
                            Name = "Book 58",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 59,
                            Author = "Author 59",
                            CategoryId = 1,
                            Description = "Test 59",
                            Name = "Book 59",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 60,
                            Author = "Author 60",
                            CategoryId = 1,
                            Description = "Test 60",
                            Name = "Book 60",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 61,
                            Author = "Author 61",
                            CategoryId = 1,
                            Description = "Test 61",
                            Name = "Book 61",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 62,
                            Author = "Author 62",
                            CategoryId = 1,
                            Description = "Test 62",
                            Name = "Book 62",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 63,
                            Author = "Author 63",
                            CategoryId = 1,
                            Description = "Test 63",
                            Name = "Book 63",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 64,
                            Author = "Author 64",
                            CategoryId = 1,
                            Description = "Test 64",
                            Name = "Book 64",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 65,
                            Author = "Author 65",
                            CategoryId = 1,
                            Description = "Test 65",
                            Name = "Book 65",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 66,
                            Author = "Author 66",
                            CategoryId = 1,
                            Description = "Test 66",
                            Name = "Book 66",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 67,
                            Author = "Author 67",
                            CategoryId = 1,
                            Description = "Test 67",
                            Name = "Book 67",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 68,
                            Author = "Author 68",
                            CategoryId = 1,
                            Description = "Test 68",
                            Name = "Book 68",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 69,
                            Author = "Author 69",
                            CategoryId = 1,
                            Description = "Test 69",
                            Name = "Book 69",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 70,
                            Author = "Author 70",
                            CategoryId = 1,
                            Description = "Test 70",
                            Name = "Book 70",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 71,
                            Author = "Author 71",
                            CategoryId = 1,
                            Description = "Test 71",
                            Name = "Book 71",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 72,
                            Author = "Author 72",
                            CategoryId = 1,
                            Description = "Test 72",
                            Name = "Book 72",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 73,
                            Author = "Author 73",
                            CategoryId = 1,
                            Description = "Test 73",
                            Name = "Book 73",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 74,
                            Author = "Author 74",
                            CategoryId = 1,
                            Description = "Test 74",
                            Name = "Book 74",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 75,
                            Author = "Author 75",
                            CategoryId = 1,
                            Description = "Test 75",
                            Name = "Book 75",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 76,
                            Author = "Author 76",
                            CategoryId = 1,
                            Description = "Test 76",
                            Name = "Book 76",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 77,
                            Author = "Author 77",
                            CategoryId = 1,
                            Description = "Test 77",
                            Name = "Book 77",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 78,
                            Author = "Author 78",
                            CategoryId = 1,
                            Description = "Test 78",
                            Name = "Book 78",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 79,
                            Author = "Author 79",
                            CategoryId = 1,
                            Description = "Test 79",
                            Name = "Book 79",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 80,
                            Author = "Author 80",
                            CategoryId = 1,
                            Description = "Test 80",
                            Name = "Book 80",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 81,
                            Author = "Author 81",
                            CategoryId = 1,
                            Description = "Test 81",
                            Name = "Book 81",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 82,
                            Author = "Author 82",
                            CategoryId = 1,
                            Description = "Test 82",
                            Name = "Book 82",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 83,
                            Author = "Author 83",
                            CategoryId = 1,
                            Description = "Test 83",
                            Name = "Book 83",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 84,
                            Author = "Author 84",
                            CategoryId = 1,
                            Description = "Test 84",
                            Name = "Book 84",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 85,
                            Author = "Author 85",
                            CategoryId = 1,
                            Description = "Test 85",
                            Name = "Book 85",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 86,
                            Author = "Author 86",
                            CategoryId = 1,
                            Description = "Test 86",
                            Name = "Book 86",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 87,
                            Author = "Author 87",
                            CategoryId = 1,
                            Description = "Test 87",
                            Name = "Book 87",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 88,
                            Author = "Author 88",
                            CategoryId = 1,
                            Description = "Test 88",
                            Name = "Book 88",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 89,
                            Author = "Author 89",
                            CategoryId = 1,
                            Description = "Test 89",
                            Name = "Book 89",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 90,
                            Author = "Author 90",
                            CategoryId = 1,
                            Description = "Test 90",
                            Name = "Book 90",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 91,
                            Author = "Author 91",
                            CategoryId = 1,
                            Description = "Test 91",
                            Name = "Book 91",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 92,
                            Author = "Author 92",
                            CategoryId = 1,
                            Description = "Test 92",
                            Name = "Book 92",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 93,
                            Author = "Author 93",
                            CategoryId = 1,
                            Description = "Test 93",
                            Name = "Book 93",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 94,
                            Author = "Author 94",
                            CategoryId = 1,
                            Description = "Test 94",
                            Name = "Book 94",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 95,
                            Author = "Author 95",
                            CategoryId = 1,
                            Description = "Test 95",
                            Name = "Book 95",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 96,
                            Author = "Author 96",
                            CategoryId = 1,
                            Description = "Test 96",
                            Name = "Book 96",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 97,
                            Author = "Author 97",
                            CategoryId = 1,
                            Description = "Test 97",
                            Name = "Book 97",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 98,
                            Author = "Author 98",
                            CategoryId = 1,
                            Description = "Test 98",
                            Name = "Book 98",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 99,
                            Author = "Author 99",
                            CategoryId = 1,
                            Description = "Test 99",
                            Name = "Book 99",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 100,
                            Author = "Author 100",
                            CategoryId = 1,
                            Description = "Test 100",
                            Name = "Book 100",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 101,
                            Author = "Author 101",
                            CategoryId = 1,
                            Description = "Test 101",
                            Name = "Book 101",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 102,
                            Author = "Author 102",
                            CategoryId = 1,
                            Description = "Test 102",
                            Name = "Book 102",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 103,
                            Author = "Author 103",
                            CategoryId = 1,
                            Description = "Test 103",
                            Name = "Book 103",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 104,
                            Author = "Author 104",
                            CategoryId = 1,
                            Description = "Test 104",
                            Name = "Book 104",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 105,
                            Author = "Author 105",
                            CategoryId = 1,
                            Description = "Test 105",
                            Name = "Book 105",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 106,
                            Author = "Author 106",
                            CategoryId = 1,
                            Description = "Test 106",
                            Name = "Book 106",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 107,
                            Author = "Author 107",
                            CategoryId = 1,
                            Description = "Test 107",
                            Name = "Book 107",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 108,
                            Author = "Author 108",
                            CategoryId = 1,
                            Description = "Test 108",
                            Name = "Book 108",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 109,
                            Author = "Author 109",
                            CategoryId = 1,
                            Description = "Test 109",
                            Name = "Book 109",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = 110,
                            Author = "Author 110",
                            CategoryId = 1,
                            Description = "Test 110",
                            Name = "Book 110",
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        });
                });

            modelBuilder.Entity("BookStore.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Category 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Category 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Category 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Category 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Category 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Category 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Category 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Category 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Category 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Category 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Category 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Category 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Category 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Category 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Category 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Category 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Category 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Category 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Category 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Category 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Category 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Category 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Category 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Category 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Category 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Category 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Category 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Category 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Category 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Category 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Category 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Category 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Category 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Category 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Category 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Category 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Category 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Category 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Category 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Category 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Category 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Category 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Category 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Category 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Category 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Category 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Category 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Category 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Category 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Category 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Category 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Category 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Category 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Category 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Category 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Category 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Category 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Category 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Category 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Category 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Category 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Category 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Category 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Category 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Category 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Category 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Category 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Category 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Category 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Category 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Category 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Category 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Category 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Category 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Category 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Category 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Category 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Category 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Category 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Category 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Category 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Category 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Category 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Category 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Category 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Category 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Category 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Category 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Category 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Category 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Category 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Category 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Category 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Category 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Category 100"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Category 101"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Category 102"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Category 103"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Category 104"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Category 105"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Category 106"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Category 107"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Category 108"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Category 109"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Category 110"
                        });
                });

            modelBuilder.Entity("BookStore.Domain.Models.Book", b =>
                {
                    b.HasOne("BookStore.Domain.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookStore.Domain.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
